import type { Metadata } from "next";
import "./globals.css";
import Footer from "./ui/elements/Footer";
import ProviderOfSession from "@/config/sessionProvider";
import ProvidersOfChakra from "@/config/chakraProvider";

export const metadata: Metadata = {
  title: "Warung Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProviderOfSession>
          <ProvidersOfChakra>{children}</ProvidersOfChakra>
        </ProviderOfSession>
        <Footer />
      </body>
    </html>
  );
}
